//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSitecore.VisualStudio.SitecoreWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Sitecore Web Service 2Soap", Namespace="http://sitecore.net/visual/", ConfigurationName="SitecoreWebService.SitecoreWebService2Soap")]
    public interface SitecoreWebService2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/CopyTo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode CopyTo(string id, string newParent, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/CopyTo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CopyToAsync(string id, string newParent, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Duplicate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Duplicate(string id, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Duplicate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DuplicateAsync(string id, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string Execute(string typeName, object[] parameters, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ExecuteAsync(string typeName, object[] parameters, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetChildren", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetChildren(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetChildren", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetChildrenAsync(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetDatabases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetDatabases(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetDatabases", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetDatabasesAsync(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetItemFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetItemFields(string id, string language, string version, bool allFields, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetItemFields", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetItemFieldsAsync(string id, string language, string version, bool allFields, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetTemplates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetTemplates(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetTemplates", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetTemplatesAsync(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string Login(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginAsync(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Save(string xml, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Save", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SaveAsync(string xml, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/AddFromMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode AddFromMaster(string id, string masterID, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/AddFromMaster", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddFromMasterAsync(string id, string masterID, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/AddFromTemplate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode AddFromTemplate(string id, string templateID, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/AddFromTemplate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddFromTemplateAsync(string id, string templateID, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/AddVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode AddVersion(string id, string language, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/AddVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddVersionAsync(string id, string language, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Delete(string id, bool recycle, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DeleteAsync(string id, bool recycle, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/DeleteChildren", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode DeleteChildren(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/DeleteChildren", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DeleteChildrenAsync(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetItemMasters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetItemMasters(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetItemMasters", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetItemMastersAsync(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetLanguages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetLanguages(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetLanguages", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLanguagesAsync(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetMasters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetMasters(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetMasters", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetMastersAsync(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetXML(string id, bool deep, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/GetXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetXMLAsync(string id, bool deep, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/InsertXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode InsertXML(string id, string xml, bool changeIDs, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/InsertXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> InsertXMLAsync(string id, string xml, bool changeIDs, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/MoveTo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode MoveTo(string id, string newParent, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/MoveTo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> MoveToAsync(string id, string newParent, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/RemoveVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode RemoveVersion(string id, string language, string version, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/RemoveVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveVersionAsync(string id, string language, string version, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Rename", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Rename(string id, string newName, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/Rename", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RenameAsync(string id, string newName, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/VerifyCredentials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode VerifyCredentials(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sitecore.net/visual/VerifyCredentials", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> VerifyCredentialsAsync(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sitecore.net/visual/")]
    public partial class Credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customDataField;
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomData {
            get {
                return this.customDataField;
            }
            set {
                this.customDataField = value;
                this.RaisePropertyChanged("CustomData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SitecoreWebService2SoapChannel : LinqToSitecore.VisualStudio.SitecoreWebService.SitecoreWebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SitecoreWebService2SoapClient : System.ServiceModel.ClientBase<LinqToSitecore.VisualStudio.SitecoreWebService.SitecoreWebService2Soap>, LinqToSitecore.VisualStudio.SitecoreWebService.SitecoreWebService2Soap {
        
        public SitecoreWebService2SoapClient() {
        }
        
        public SitecoreWebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SitecoreWebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitecoreWebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitecoreWebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode CopyTo(string id, string newParent, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.CopyTo(id, newParent, name, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CopyToAsync(string id, string newParent, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.CopyToAsync(id, newParent, name, databaseName, credentials);
        }
        
        public System.Xml.XmlNode Duplicate(string id, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.Duplicate(id, name, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DuplicateAsync(string id, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.DuplicateAsync(id, name, databaseName, credentials);
        }
        
        public string Execute(string typeName, object[] parameters, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.Execute(typeName, parameters, credentials);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteAsync(string typeName, object[] parameters, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.ExecuteAsync(typeName, parameters, credentials);
        }
        
        public System.Xml.XmlNode GetChildren(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetChildren(id, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetChildrenAsync(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetChildrenAsync(id, databaseName, credentials);
        }
        
        public System.Xml.XmlNode GetDatabases(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetDatabases(credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetDatabasesAsync(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetDatabasesAsync(credentials);
        }
        
        public System.Xml.XmlNode GetItemFields(string id, string language, string version, bool allFields, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetItemFields(id, language, version, allFields, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetItemFieldsAsync(string id, string language, string version, bool allFields, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetItemFieldsAsync(id, language, version, allFields, databaseName, credentials);
        }
        
        public System.Xml.XmlNode GetTemplates(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetTemplates(databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetTemplatesAsync(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetTemplatesAsync(databaseName, credentials);
        }
        
        public string Login(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.Login(credentials);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.LoginAsync(credentials);
        }
        
        public System.Xml.XmlNode Save(string xml, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.Save(xml, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SaveAsync(string xml, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.SaveAsync(xml, databaseName, credentials);
        }
        
        public System.Xml.XmlNode AddFromMaster(string id, string masterID, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.AddFromMaster(id, masterID, name, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddFromMasterAsync(string id, string masterID, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.AddFromMasterAsync(id, masterID, name, databaseName, credentials);
        }
        
        public System.Xml.XmlNode AddFromTemplate(string id, string templateID, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.AddFromTemplate(id, templateID, name, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddFromTemplateAsync(string id, string templateID, string name, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.AddFromTemplateAsync(id, templateID, name, databaseName, credentials);
        }
        
        public System.Xml.XmlNode AddVersion(string id, string language, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.AddVersion(id, language, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddVersionAsync(string id, string language, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.AddVersionAsync(id, language, databaseName, credentials);
        }
        
        public System.Xml.XmlNode Delete(string id, bool recycle, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.Delete(id, recycle, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DeleteAsync(string id, bool recycle, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.DeleteAsync(id, recycle, databaseName, credentials);
        }
        
        public System.Xml.XmlNode DeleteChildren(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.DeleteChildren(id, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DeleteChildrenAsync(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.DeleteChildrenAsync(id, databaseName, credentials);
        }
        
        public System.Xml.XmlNode GetItemMasters(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetItemMasters(id, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetItemMastersAsync(string id, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetItemMastersAsync(id, databaseName, credentials);
        }
        
        public System.Xml.XmlNode GetLanguages(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetLanguages(databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLanguagesAsync(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetLanguagesAsync(databaseName, credentials);
        }
        
        public System.Xml.XmlNode GetMasters(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetMasters(databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetMastersAsync(string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetMastersAsync(databaseName, credentials);
        }
        
        public System.Xml.XmlNode GetXML(string id, bool deep, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetXML(id, deep, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetXMLAsync(string id, bool deep, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.GetXMLAsync(id, deep, databaseName, credentials);
        }
        
        public System.Xml.XmlNode InsertXML(string id, string xml, bool changeIDs, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.InsertXML(id, xml, changeIDs, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> InsertXMLAsync(string id, string xml, bool changeIDs, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.InsertXMLAsync(id, xml, changeIDs, databaseName, credentials);
        }
        
        public System.Xml.XmlNode MoveTo(string id, string newParent, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.MoveTo(id, newParent, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> MoveToAsync(string id, string newParent, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.MoveToAsync(id, newParent, databaseName, credentials);
        }
        
        public System.Xml.XmlNode RemoveVersion(string id, string language, string version, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.RemoveVersion(id, language, version, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveVersionAsync(string id, string language, string version, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.RemoveVersionAsync(id, language, version, databaseName, credentials);
        }
        
        public System.Xml.XmlNode Rename(string id, string newName, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.Rename(id, newName, databaseName, credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RenameAsync(string id, string newName, string databaseName, LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.RenameAsync(id, newName, databaseName, credentials);
        }
        
        public System.Xml.XmlNode VerifyCredentials(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.VerifyCredentials(credentials);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> VerifyCredentialsAsync(LinqToSitecore.VisualStudio.SitecoreWebService.Credentials credentials) {
            return base.Channel.VerifyCredentialsAsync(credentials);
        }
    }
}
